### ISSUE TITLE
Week of August 27th

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Open-Sentencing#25]
**Sprint Priorities**  updated 9/3/21

- [ ] Documentation updates (@demilolu)
- [ ] CI/CD for aggregators to deploy easily to cloud
- [x] Rick to create list of reporters (sent in Slack, IBM team has to check about contacting reporters)
- [ ] Generate swagger from Java classes Rick
- [ ] App ID authentication for aggregator @yochanah 
- [x] Demo of Akilah's UI changes: updating actual UI to be similar to prototype  (in progress, more will be done next week)
- [ ] Shift to aggregator to create dummy data for UI Akilah
- [x] @upkarlidder add Akilah and Rick

**Done**
- Aggregator in code engine  @upkarlidder 

**Tasks**

**Decision Points**
- Aggregator redo: net-new : authentication, (Decision made, will keep current one and modify as needed)

- Discussion on changing database (from Cloudant - more suitable for big data that's static), with our cases and attorneys we need something dynamic. Move to: DB2?  (look like we'll stick with Cloudant for a while)

- moving to jHipster vs Liberty  (same as above)

**Community Decisions**

- Moving authentication to back-end

- switching to be aggregator to be class and not swagger based  (Rick has started research week of 9/3)
**Blockers**
