### ISSUE TITLE
Week of September 10th - September 24th

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Open-Sentencing#26]
**Sprint Priorities** 

- [x] merge UI update PRs (@upkarlidder @wisdomkeeper) (UI)
- [ ] Documentation updates (@demilolu) - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/27
- [ ] Unit Testing!!! @RickPoleshuck : all repos:
-  https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/28#issue-996449300
-  https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Model/issues/13  
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/61

- [ ] (manual deployment) @upkarlidder : aggregator/UI: 
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/29
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/62
- [ ] CI/CD for aggregators to deploy easily to cloud (automated deployment) @RickPoleshuck  : aggregator/UI
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/30
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/63
- [ ] Generate swagger from Java classes @RickPoleshuck aggregator
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/31
- [ ] App ID authentication for aggregator @yochanah (aggregator) - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/22
- [ ] Shift to aggregator to create dummy data for UI Akilah (aggregator) - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/32
- [ ] Creating Data requirements that we need @sforsyth089 @joannhh  (general) - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/29#issue-996451761  (This is a group activity that will include many people)

**Done**

- [x] #33
- [x] new issue for bug for App ID error @wisdomkeeper https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/56

**Under Review**
- [ ] [modal components for validation using Carbon design  components](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/pull/57) to make more like Vue 
- [ ] removing bootstrap styles and adding carbon design on UI
- [ ] style changes to log-in page Under review
- [ ] @ulmasov with PR  https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/pull/69 to fix https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/65

**Tasks**

- [x] create issues based on sprint priorities

**Blockers**
- missing back-end data
- App ID Authentication for @wisdomkeeper (single page app error) 
- Build failing on main branch 

**Bugs**
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/59
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/56

**Decision Points**
- Update Angular CLI - 12.0.5 ? 9? - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/51

**Community Decisions**
- Keeping aggregator as is
- Staying with jHipster
- Staying with Cloudant for awhile 
- Moving authentication to back-end
-  switching to be aggregator to be class and not swagger based (Rick has started research week of 9/3)

**Community Requests:**
- Finding sources of data: We need group resources to help find more data.  See the issue below and add to the Excel document anything you find!  Mark as investigating and we can talk at our weekly meetings.
- Federal Data may need more pull down/clean-up. Stacy will research and follow up/add a task. (could be a hacktoberfest item)
- Siran will research the data from Cook County to see what attributes get passed through and how to pull in new data.
- We need the bias output to pass through the UI.  Siran/Stacy/Akilah will connect.
-Please see this issue: https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/31

**Comment by upkarlidder** [comment]
@demilolu we finished `merge UI update PRs`.

Thanks to @wisdomkeeper!
