### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Open-Sentencing#27]
### Background on the problem the feature will solve/improved user experience
New users to Open Sentencing might be a little confused in following the documentation

### Describe the solution you'd like
Suggest updates to documentation

### Tasks 

- [ ] Review documentation
- [ ] Recruit community memebrs to review/hack a doc
- [ ] Open new issues for documentation updates
- [ ] Review suggested changes with team
- [ ] Commit changes to documentation 

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.
