### ISSUE TITLE
Create data requirements

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Open-Sentencing#29]
### Background on the problem the feature will solve/improved user experience
Our app currently lacks the data we need to be able to provide public defenders with statistics they need on 

### Describe the solution you'd like
We need to gather and specify our data requirements for the open sentencing app. 

### Tasks 

- [ ] Map out user journey
- [ ] Identify data needed at each step
- [ ] identify potential sources of data
- [ ] identify risks/considerations associated with data gathering

### Acceptance Criteria 

Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.

**Comment by sforsyth089** [comment]
We found our old requirements on Box. I would like to discuss at our meeting tomorrow (attached).
[Intake,Initiation,Disposition,Sentencing,Diversion.xlsx](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/files/7180307/Intake.Initiation.Disposition.Sentencing.Diversion.xlsx)
[Mapping between Open Sentencing and Outcarcerate Schema v1.xlsx](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/files/7180308/Mapping.between.Open.Sentencing.and.Outcarcerate.Schema.v1.xlsx)

[Data Sources that would improve our MVP.docx](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/files/7180309/Data.Sources.that.would.improve.our.MVP.docx)

**Comment by demilolu** [comment]
ok sweet!

**Comment by upkarlidder** [comment]
Is this related to `Collect more data on plea stage to build out reporting later on how the tool is working ` that came out of the design thinking session?

**Comment by joannhh** [comment]
Meeting held on 10/23/21 (Hui/Stacy/Jo Ann)
- Discussed that Hui and Tyler reviewed NY State database and saw that it's similar to Cook County
- Hui will have Tyler to share the NY State email request with Stacy so that the context can be incorporated into the overall data collection task
- Based on additional research, Florida would possibly be a good target dataset: http://www.dc.state.fl.us/pub/obis_request.html (Hui will research further)
- Jo Ann and Stacy to continue to search for others and update the tracking spreadsheet
- Siran may be needed to help provide background assistance for some linear regression

**Comment by upkarlidder** [comment]
FYI @Corey-keyser
