### ISSUE TITLE
Week of September 25 - October 29 (extended)

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Open-Sentencing#32]
**Sprint Priorities** 

New info: Rensselaer Polytechnic Institute offered to help us out.  Upkar will talk on Slack/add to the meeting.

- [x] merge UI update PRs (@upkarlidder @wisdomkeeper) (UI) Upkar finishing
  - [x] https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/pull/79
- [ ] Documentation updates (@demilolu) - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/27
- [ ] Unit Testing!!! @RickPoleshuck : all repos:
-  https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/28#issue-996449300
-  https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Model/issues/13  
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/61
- Related PRs (@upkarlidder to review)
   - [ ] https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/pull/27
   

- [ ] CI/CD for aggregators to deploy easily to cloud (automated deployment) @RickPoleshuck  : aggregator/UI
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/30
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/63
   - [ ] https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/pull/20 @upkarlidder to review
- [ ] Generate swagger from Java classes @RickPoleshuck aggregator
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/31
- [ ] App ID authentication for aggregator @yochanah (aggregator) - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/22  [depends on earlier [issue](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/31) Rick working on- updated in issue]
- [ ] Shift to aggregator to create dummy data for UI Akilah (aggregator) - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/32 [dependent on API/back-end] Stacy/Akilah will connect with @siranjujugi
  - need updates 
- [ ] Creating Data requirements that we need @sforsyth089 @joannhh  (general) - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/29#issue-996451761  [Want to think about better break-ups of tasks]  (we are finding lacking data that has race info) 
   - @joannhh and @sforsyth089 talked to Hui. Issue needs updating.
-  Identify risk considerations goes along with data gathering - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/31
- [ ] Data cleaning and collection work with Hui -https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/34

- [x] Akilah's UI updates: updating actual UI to be similar to prototype PRs here: 
- [x] new issue for bug for App ID error @wisdomkeeper https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/56

**Tasks**
- [ ] create user skill list for reference (time zones, skills, etc.) @sforsyth089 https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/48
- [x] create issues based on sprint priorities
- [ ] Hui and Jeff and Tyler (have them create forks while working on tasks, once commitment made add to repo)
- [ ] Jeff to take a look at unit testing for aggregator @ulmasovjafarbek
- [ ] Hui to work on data collections once meeting is set up (need meeting, Jo Anne will set up)
- [x] Set date for meeting on datasets, data model, required data led by @sforsyth089 @siranjujugi  @joannhh (will happen next week)
- [x] Follow up on issues and assignments in regards to Hacktoberfest, RCOS, etc. 
- [x] Akilah @wisdomkeeper - can help with identifying good first issues, and rules of engagement for Hacktoberfest
- [x] Resolved unclear Readme

**Blockers**
- [ ] missing back-end data -  https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/32
- [x] App ID Authentication for @wisdomkeeper (single page app error) 
- [  ] Build failing on main branch @upkarlidder to test

**Bugs**
- [x] https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/59 (fixed with PR81, @upkarlidder to test and close the issue)
- [x] https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/56

**Decision Points**
-[x] Update Angular CLI - 12.0.5 ? 9? - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/51
  Carbon Discord chat: https://discord.gg/SYjvP8epkM

**Community Decisions**
- Keeping aggregator as is
- Staying with OpenLiberty
- Staying with Cloudant for awhile 
- Moving authentication to back-end
-  switching to be aggregator to be class and not swagger based (Rick has started research week of 9/3)

**Community Requests:**
- Finding sources of data: Lots of HELP WANTED! 

Deprioritized til demo sites/ are needed/ 
- [ ] (manual deployment) @upkarlidder : aggregator/UI: 
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/29  (closed)
- https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/62 (in-progress)
