### ISSUE TITLE
Gathering sentencing data across states & counties (Cohort)

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Open-Sentencing#50]
### Description & Problem Statement
Sentencing for various charges might differ by county, etc. Thus granularity of location is needed to better assess potential racial bias in sentencing. 

## Solution
Gather new data sources for sentencing data from various counties, states. 

### Resources
- [Swagger file ](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/blob/main/src/main/resources/swagger.yaml) of open sentencing fields
- [Data source checklist](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/31)
- 
### Tasks 

- [ ] Review Swagger to determine exact fields needed from candidate data set to provide relevant sentencing data
- [ ] [Review data source checklist here](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/31)
- [ ] Research candidate sentencing data sources and evaluate them against our data source checklist
-

### Acceptance Criteria 
- Define and confirm fields needed 
-

**Comment by demilolu** [comment]
Add:
- list of data we have added already
- list of datasets we've reached out to
- template for outreach

**Comment by sforsyth089** [comment]
https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/31
Refer to this issue for our running list of items.

**Comment by sforsyth089** [comment]
Duplicate, See Epic #31
