### ISSUE TITLE
Sprint 4: Nov 8 - Nov 19, 2021

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Open-Sentencing#51]
**Sprint Priorities** 
- [ ] https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues/63
- [ ] https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/pull/20 @upkarlidder to review
- [ ] Creating Data requirements that we need @sforsyth089 @joannhh  (general) - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/29#issue-996451761  [Want to think about better break-ups of tasks]  (we are finding lacking data that has race info) 
   - @joannhh and @sforsyth089 talked to Hui. Issue needs updating.
-  Identify risk considerations goes along with data gathering - https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/31
- [ ] UI: Improve dashboard (look and responsiveness) @wisdomkeeper 
- [ ] Upgrading Angular versioning @wisdomkeeper 

**Tasks**
- [ ] create user skill list for reference (time zones, skills, etc.) @sforsyth089 https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/issues/48
- [ ] sync with @yochanah on support for backend issues
- [ ] Hui and Jeff and Tyler (have them create forks while working on tasks, once commitment made add to repo)
- [ ] Hui to work on data collections once meeting is set up (need meeting, Jo Anne will set up)
- [ ] define data work for external cohort 

**Blockers**
- [ ] missing back-end data -  https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/32
- [  ] Build failing on main branch @upkarlidder to test

**Bugs**

**Decision Points**

**Community Decisions**

**Community Requests:**
- Finding sources of data: Lots of HELP WANTED!

**Comment by sforsyth089** [comment]
New Sprint started
