### ISSUE TITLE
Transfer user stories to readme

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Open-Sentencing#66]
### Background on the problem the feature will solve/improved user experience
@sforsyth089  created user stories for #52. We need to transfer them to a md file in the main repo. 

### Describe the solution you'd like
@wisdomkeeper
 - [ ] create usecases.md file
 - [ ] add link to the main readme as a subsection after the video

### Tasks 
 - [ ] create usecases.md file
 - [ ] add to the main readme as a subsection after the video

### Acceptance Criteria 
The user stories have been copied to the main repository.

**Comment by sforsyth089** [comment]
@wisdomkeeper will update design for us to react to

**Comment by joannhh** [comment]
#75 Related to this one, looking for a new user story. The decision point is to add user stories to the Assets folder and direct people there.
