### ISSUE TITLE
Investigate feature to target states that have data available

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Open-Sentencing#68]
### Background on the problem the feature will solve/improved user experience
The solution does not have data for all states. 

### Describe the solution you'd like
Add a component to the solution that filters by state.

### Tasks 
- [ ] ask for state before the `add a case` step
- [ ] redirect to modal that either
   - [ ] takes to use to the bias detector if state data is available
   - [ ] notifies the user to petition for state data 

@wisdomkeeper 

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.
